### ISSUE TITLE
Feature request: Adding links/urls

### ISSUE THREAD

**Issue by CKenberg** [ClimberAB/ClimberCards#2]
This extension is fantastic (thank you so much!) ...but it would even more fantastic if you can add links (like "Representation = URL" in the regular tables). So that when you click the third dimension (in our case a title for a given product) in could be a link taking you directly to the url (in our case a product page).

Thanks again,
Claus

![capture](https://cloud.githubusercontent.com/assets/27813709/25231106/d1ce6f1a-25d6-11e7-8748-67a8e81e4a92.JPG)

**Comment by cl-edwardhallgren** [comment]
Thanks for your input!

We will consider to implement this in a future verison.

Br
Edward

**Comment by edwardhallgren** [comment]
We will add this feature request to our other private repository.

We have a subscription model for our extensions (supported). If you are interested, please contact us.

Br
Edward
