### ISSUE TITLE
Feature request: Remove/toggle "Rank"

### ISSUE THREAD

**Issue by CKenberg** [ClimberAB/ClimberCards#3]
Once again, thank you for a fantastic extension. However, it would be even better, if it was possible to select/deselect whether or not to show the rank.

Thanks again,
Claus

![capture2](https://cloud.githubusercontent.com/assets/27813709/25234776/689e59bc-25e3-11e7-8293-99ec735f0903.JPG)

**Comment by cl-edwardhallgren** [comment]
![feature](https://cloud.githubusercontent.com/assets/27728137/25346194/3f4ad342-2917-11e7-85d1-06a8bff08bc7.png)

Thanks for your input.
We have now implemented this feature in 1.1.2. 

Br
//Edward
