### ISSUE TITLE
Server images or Local images

### ISSUE THREAD

**Issue by alemate88** [ClimberAB/ClimberCards#5]
### Server images or Local images

If the url image is on web like the one in the example it shows, but I want to display  local images stored in C: or other server (\\servername\image.jpg)

### Steps to Reproduce

1. Add as 1st dimension my id field
2. Add as 2nd dimension my url field 
3. Add as 3rd dimension other field
4. Add a measure

##### Expected behavior

The normal behavior

##### Actual behavior

Can't display the images

### Environment
```
[ ] Desktop
[X ] Enterprise
```
### Versions

* Extension version:
* Browser: Internet Explorer 11 & Chrome
* Qlik Sense: September 2017
* Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
* [Other relevant versions]

### Screenshots

![image](https://user-images.githubusercontent.com/34113457/33408437-18cc6a7e-d53c-11e7-9833-3b14bc62c241.png)

**Comment by alemate88** [comment]
the issue was solved by changing the url of the file:

file://servername/location/image.jpg

but only works on internet explorer not chrome

**Comment by MichaelClimber** [comment]
Hi, 
this is intentional. It should not be possible to access local files from the Chrome browser. You have the options of putting files in the content library or setting up a web server with the files. 

/Michael
