### ISSUE TITLE
Idea: Make it possible to associate an URL with each card

### ISSUE THREAD

**Issue by mountaindude** [ClimberAB/ClimberCards#6]
Being able to move to another sheet when clicking a card is great.
A more common scenario (at least for me) is that I want to link to some external web resource. Would thus be useful to associate a URL with each card.

**Comment by MichaelClimber** [comment]
Hi Göran,
Thank you for your input. I agree it is a good idea. We have this on our internal wish-list for the extension but no customer requests yet so we have not made it a priority.
