### ISSUE TITLE
Visualization not found on the server 

### ISSUE THREAD

**Issue by sbrusse** [ClimberAB/ClimberCards#7]
### Description

I've recently upgraded Qlik Sense Enterprise to June 2018. Since the upgrade I have an issue with the Cards extension in a published app. If I'm the owner of the published app I can see the extension object, but if I'm not the owner and I open the published app I get an error message "The visualization is not found on the server: cl-cards". 

### Steps to Reproduce

1. Create new app with cards extension
2. Publish app to stream
3. Open app in stream
4. Change owner of the pbulished app
5. Open app in stream

### Environment
```
[ ] Desktop
[x ] Enterprise
```
### Versions

* Extension version: 1.3.0
* Browser: Chrome
* Qlik Sense: Qlik Sense Enterprise June 2018
* Operating system: Windows 2016
* [Other relevant versions]

### Screenshots
![capture](https://user-images.githubusercontent.com/6149822/44449153-a0e51500-a5ed-11e8-9c61-778989baa54a.PNG)

**Comment by edwardhallgren** [comment]
Hi, could you try to clear the cache in your web browser and see if problem still remains. (https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en).
Br Edward

**Comment by patakess** [comment]
Hi,
Same behaviour for me. If I change the owner of the published app it works for him (only for him).
Same versions as Sbrusse
Controled on Chrome and Edge

**Comment by sbrusse** [comment]
Hi Edward,

I tried to clear the cache, used different browsers (FF, IE, Chrome), re-install the extension, but the issue still remains.

Best,
Steven

**Comment by patakess** [comment]
I've downgraded to 1.2.2. It works.

**Comment by edwardhallgren** [comment]
This works in version 1.3.1. Br Edward
