### ISSUE TITLE
Images not showing when source loaded via LOAD*INLINE

### ISSUE THREAD

**Issue by ftinelli** [ClimberAB/ClimberCards#8]
Versions
* Extension version: 1.4.1
* Qlik Sense: Qlik Sense Desktop 12.44.1
* Browser: Chrome 

Description
When I use the below lines in the data load editor to upload images, the images do not display in the extension.

Images:
LOAD * INLINE [

    ID, ImageName, ImageLocation

    1, feather1, 'http://localhost:4848/content/default/Qlik_default_feathers.png'
    6, movie2, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY67_CR1,0,45,67_AL_.jpg'

];

Steps to Reproduce

1. Upload image sources by above data load editor lines
2. Add as 1st dimension, ID field
3. Add as 2nd dimension, ImageLocation field
4. Add as 3rd dimension, ImageName field
5. Add a measure, count of ID field

Expected behavior

See the dimensions, especially the images.

Actual Behavior & Screen Shot

No images displayed.
<img width="88" alt="imageissue" src="https://user-images.githubusercontent.com/46359546/50674864-f24bda80-0fb7-11e9-8313-31fd5e2f2f2b.PNG">

**Comment by kfsjostrand** [comment]
Hi @ftinelli,
I'm using your load script and it works fine in Chrome. 
![image](https://user-images.githubusercontent.com/20219900/50819329-041bdd80-132a-11e9-8fe0-ec1b60793ef9.png)

It's better to use the relative path to the content library if you want to publish your app on a server. 
Like this `1, feather1, '../content/default/Qlik_default_feathers.png'`

Do you get any error messages in the console `Ctrl + Shift + j`?
Regards
Karl

**Comment by kfsjostrand** [comment]
Can't recreate the issue.
