### ISSUE TITLE
Selection issue

### ISSUE THREAD

**Issue by Phreakje** [ClimberAB/ClimberCards#9]
### Versions
Extension version: 1.5.0
Qlik Sense: February 2019
Browser:  Chrome

### Description
When de-selecting items in the extension object, they wont clear from the filter:
![image](https://user-images.githubusercontent.com/5197103/55555750-444eea00-56e6-11e9-9d7d-cc95d02d222f.png)

### Console errors
None

### Steps to Reproduce
1. Click on multiple items in the object
2. Deselect one or multiple from the current selection
3. Notice that the deselected items wont clear from the selection in Qlik Sense

##### Expected behavior
Deselecting items in the object itself clears the item selection in Qlik Sense aswell

**Comment by MichaelClimber** [comment]
All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions.
